/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    BtnCustom: typeof import('./src/components/buttons/btn-custom.vue')['default']
    BtnTooltip: typeof import('./src/components/buttons/btn-tooltip.vue')['default']
    CardDialog: typeof import('./src/components/cards/card-dialog.vue')['default']
    CardForm: typeof import('./src/components/cards/card-form.vue')['default']
    CardTable: typeof import('./src/components/cards/card-table.vue')['default']
    CartTable: typeof import('./src/components/cards/cart-table.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IteratorHeader: typeof import('./src/components/iterators/iterator-header.vue')['default']
    LoadingOverlay: typeof import('./src/components/dashboard/loading-overlay.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
